// frontend/src/data.js
export const bookData = [
    {
        id: 1,
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        price: '12.00',
        image: '/images/pride and prejudice book.jpg',
        category: 'Literary Works',
        plot: 'A witty and insightful novel following the evolving relationship between Elizabeth Bennet and Mr. Darcy, exploring themes of love, class, and societal expectations in 19th-century England.',
    },
    {
        id: 2,
        title: 'Cosmos',
        author: 'Carl Sagan',
        price: '15.50',
        image: '/images/Cosmos Carl Sagan book.jpeg',
        category: 'Informative Reads',
        plot: 'A captivating journey through the universe, exploring astronomy, cosmology, and the wonders of the cosmos in an accessible and engaging way, based on the iconic television series.',
    },
    {
        id: 3,
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        price: '10.75',
        image: '/images/the hobbit book.jpeg',
        category: 'Teen & Children',
        plot: 'An adventurous tale of Bilbo Baggins, a reluctant hobbit who is swept away on an unexpected quest with a company of dwarves to reclaim their treasure from the dragon Smaug.',
    },
    {
        id: 4,
        title: 'The Secret History',
        author: 'Donna Tartt',
        price: '18.00',
        image: '/images/the secret history book.jpg',
        category: 'Literary Works',
        plot: 'A mesmerizing story about a group of eccentric classics students at a New England college who become entangled in a dark and tragic secret after experimenting with ancient Greek rituals.',
    },
    {
        id: 5,
        title: 'Thinking, Fast and Slow',
        author: 'Daniel Kahneman',
        price: '22.00',
        image: '/images/thinking, fast and slow book.jpeg',
        category: 'Informative Reads',
        plot: 'A groundbreaking exploration of the two systems that drive the way we think: System 1, which is fast, intuitive, and emotional; and System 2, which is slower, more deliberative, and more logical.',
    },
    {
        id: 6,
        title: 'The Hunger Games',
        author: 'Suzanne Collins',
        price: '9.99',
        image: '/images/the hunger games book.jpg',
        category: 'Teen & Children',
        plot: 'In a dystopian future, Katniss Everdeen volunteers as tribute in the annual Hunger Games, a televised fight to the death, sparking a rebellion against the oppressive Capitol.',
    },
    {
        id: 7,
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        price: '14.50',
        image: '/images/to kill a mockingbird book.jpg',
        category: 'Literary Works',
        plot: 'Set in the American South, this classic novel explores themes of racial injustice and childhood innocence through the eyes of Scout Finch as her father, Atticus, defends a Black man accused of a crime.',
    },
    {
        id: 8,
        title: 'A Brief History of Time',
        author: 'Stephen Hawking',
        price: '18.25',
        image: '/images/a brief history of time book.jpg',
        category: 'Informative Reads',
        plot: 'A non-technical exploration of the history of the universe and concepts such as black holes, the Big Bang, and the nature of space and time, making complex ideas accessible to a broad audience.',
    },
    {
        id: 9,
        title: 'Harry Potter and the Sorcerer\'s Stone',
        author: 'J.K. Rowling',
        price: '11.00',
        image: '/images/harry potter and the sorcerer\'s stone book.jpg',
        category: 'Teen & Children',
        plot: 'Orphaned Harry Potter discovers on his eleventh birthday that he is a wizard and is invited to study at Hogwarts School of Witchcraft and Wizardry, where he uncovers the truth about his parents\' deaths and confronts a dark wizard.',
    },
    {
        id: 10,
        title: '1984',
        author: 'George Orwell',
        price: '13.75',
        image: '/images/1984 book.jpg',
        category: 'Literary Works',
        plot: 'A dystopian novel set in Oceania, where the Party, led by Big Brother, maintains absolute control over every aspect of life, and Winston Smith rebels against the oppressive regime.',
    },
    {
        id: 11,
        title: 'Educated: A Memoir',
        author: 'Tara Westover',
        price: '20.00',
        image: '/images/educated book.jpg',
        category: 'Informative Reads',
        plot: 'A powerful memoir about a young woman raised in a survivalist family in rural Idaho who overcomes her lack of formal education to pursue knowledge and ultimately earns a PhD from Cambridge University.',
    },
    {
        id: 12,
        title: 'The Lightning Thief (Percy Jackson & The Olympians Book 1)',
        author: 'Rick Riordan',
        price: '8.50',
        image: '/images/the lightning thief (percy jackson & the olympians) book.jpg',
        category: 'Teen & Children',
        plot: 'Percy Jackson, a teenager who discovers he is the son of the Greek god Poseidon, embarks on a quest with his friends to prevent a war among the gods after Zeus\'s master lightning bolt is stolen.',
    },
    {
        id: 201,
        title: 'Book Ends (Set of 2)',
        author: 'Generic Brand',
        price: '15.00',
        image: '/images/book_ends.jpg',
        category: 'Other Items',
        description: 'A sturdy set of two book ends...',
    },
    {
        id: 202,
        title: 'Literary Tote Bag',
        author: 'The Bookstore Co.',
        price: '22.00',
        image: '/images/tote_bag.jpg',
        category: 'Other Items',
        description: 'A stylish and durable tote bag...',
    },
    {
        id: 300, 
        title: 'The Girl with the Dragon Tattoo',
        author: 'Stieg Larsson',
        price: '16.99',
        image: '/images/dragon_tattoo.jpg',
        category: 'Mystery',
        plot: 'A journalist and a troubled hacker team up to investigate the disappearance of a young woman from a wealthy family.',
    },
];